version: "3.8"

services:
  api:
    build: .
    container_name: home-assistant
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://tudruj:secret@postgres:5432/homeassistant
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: home-assistant-db
    environment:
      POSTGRES_USER: tudruj
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homeassistant
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
